env:
  es6: true
  node: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  indent: [ error, 4 ]
  operator-linebreak: [ error, after ]
  quotes: [ error, backtick ]
  arrow-parens: [ error, as-needed ]
  comma-dangle: [ error, never ]
  array-bracket-spacing: [ error, always ]
  no-underscore-dangle: 0
  no-plusplus: 0
  no-continue: 0
  no-await-in-loop: 0
